<<<<<<< HEAD
# Generated by Django 5.1.3 on 2024-12-04 13:35
=======
# Generated by Django 5.1.3 on 2024-12-01 23:46
>>>>>>> 18c34b6243b7ecca8b79329a6c5b8cc51857778c

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='HistoricoPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('ativo', models.CharField(max_length=10)),
                ('quantidade', models.IntegerField()),
                ('preco_medio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(max_length=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'indexes': [models.Index(fields=['data'], name='proventos_h_data_c283a1_idx'), models.Index(fields=['ativo'], name='proventos_h_ativo_ff7e1d_idx')],
                'unique_together': {('data', 'ativo')},
            },
        ),
        migrations.CreateModel(
            name='ProventoAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.CharField(max_length=10)),
                ('data_com', models.DateField()),
                ('data_pagamento', models.DateField(null=True)),
                ('tipo_provento', models.CharField(max_length=20)),
                ('valor_provento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('por_quantas_acoes', models.IntegerField(default=1)),
            ],
            options={
                'indexes': [models.Index(fields=['ativo'], name='proventos_p_ativo_457229_idx'), models.Index(fields=['data_com'], name='proventos_p_data_co_605284_idx')],
            },
        ),
        migrations.CreateModel(
            name='RendimentoFII',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.CharField(max_length=10)),
                ('data_com', models.DateField()),
                ('data_rendimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'indexes': [models.Index(fields=['ativo'], name='proventos_r_ativo_e4720e_idx'), models.Index(fields=['data_com'], name='proventos_r_data_co_6f62ef_idx')],
=======
            name='Provento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(max_length=10)),
                ('tipo_provento', models.CharField(max_length=50)),
                ('quantidade', models.IntegerField()),
                ('valor_provento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_com', models.DateField()),
                ('data_pagamento', models.DateField(null=True)),
            ],
            options={
                'ordering': ['-data_com'],
>>>>>>> 18c34b6243b7ecca8b79329a6c5b8cc51857778c
            },
        ),
    ]
