# Generated by Django 5.1.3 on 2024-12-01 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(max_length=10)),
                ('tipo_provento', models.CharField(max_length=50)),
                ('quantidade', models.IntegerField()),
                ('valor_provento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_com', models.DateField()),
                ('data_pagamento', models.DateField(null=True)),
            ],
            options={
                'ordering': ['-data_com'],
            },
        ),
    ]
