# Generated by Django 5.1.3 on 2024-12-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proventos', '0002_alter_historicoportfolio_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(max_length=10)),
                ('data_com', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('tipo_provento', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['-data_com'],
            },
        ),
        migrations.DeleteModel(
            name='ProventoAcao',
        ),
        migrations.DeleteModel(
            name='RendimentoFII',
        ),
    ]
