# Generated by Django 5.1.3 on 2024-12-06 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proventos', '0003_provento_delete_proventoacao_delete_rendimentofii'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Provento',
            new_name='ProventoAcao',
        ),
    ]
