# Generated by Django 5.1.3 on 2024-12-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proventos', '0004_rename_provento_proventoacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proventoacao',
            options={'ordering': ['-data_com', 'papel']},
        ),
        migrations.AddField(
            model_name='proventoacao',
            name='quantidade_acoes',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='proventoacao',
            name='valor',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
