# Generated by Django 5.1.3 on 2024-12-06 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proventos', '0005_alter_proventoacao_options_and_more'),
    ]

    operations = [
    ]
