# Generated by Django 5.0.3 on 2024-06-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransacoesConsolidadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, db_column='Data', null=True)),
                ('operacao', models.TextField(blank=True, db_column='Operacao', null=True)),
                ('ativo', models.TextField(blank=True, db_column='Ativo', null=True)),
                ('quantidade', models.IntegerField(blank=True, db_column='Quantidade', null=True)),
                ('preço', models.FloatField(blank=True, db_column='Preço', null=True)),
            ],
            options={
                'db_table': 'transacoes_consolidadas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransacoesMonica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, db_column='Data', null=True)),
                ('operacao', models.TextField(blank=True, db_column='Operacao', null=True)),
                ('ativo', models.TextField(blank=True, db_column='Ativo', null=True)),
                ('quantidade', models.IntegerField(blank=True, db_column='Quantidade', null=True)),
                ('preço', models.FloatField(blank=True, db_column='Preço', null=True)),
            ],
            options={
                'db_table': 'transacoes_monica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransacoesSilmar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, db_column='Data', null=True)),
                ('operacao', models.TextField(blank=True, db_column='Operacao', null=True)),
                ('ativo', models.TextField(blank=True, db_column='Ativo', null=True)),
                ('quantidade', models.IntegerField(blank=True, db_column='Quantidade', null=True)),
                ('preço', models.FloatField(blank=True, db_column='Preço', null=True)),
            ],
            options={
                'db_table': 'transacoes_silmar',
                'managed': False,
            },
        ),
    ]
