# Generated by Django 5.1.3 on 2024-12-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao_Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Movimentação de Ativo',
                'verbose_name_plural': 'Movimentações de Ativos',
            },
        ),
    ]
