# Generated by Django 5.0.3 on 2024-06-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carteira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Ação', 'Ação'), ('FII', 'FII'), ('ETF', 'ETF')], max_length=20)),
                ('quantidade', models.IntegerField()),
                ('preco_medio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('patrimonio_atual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ganho_perda', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
