# Generated by Django 5.1.3 on 2024-11-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarteiraConsolidada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.CharField(max_length=10)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_atual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_atualizacao', models.DateTimeField()),
            ],
            options={
                'db_table': 'carteira_consolidada',
            },
        ),
        migrations.CreateModel(
            name='CarteiraMonica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.CharField(max_length=10)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_atual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_atualizacao', models.DateTimeField()),
            ],
            options={
                'db_table': 'carteira_monica',
            },
        ),
        migrations.CreateModel(
            name='CarteiraSilmar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.CharField(max_length=10)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_atual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_atualizacao', models.DateTimeField()),
            ],
            options={
                'db_table': 'carteira_silmar',
            },
        ),
    ]
