name = "controle-financeiro"
type = "python"
workers_dev = true
compatibility_date = "2024-01-01"

[build]
command = "pip install -r requirements.txt"

[env.production]
name = "controle-financeiro-prod"

[site]
bucket = "./static"
